export const CARDS = {
  padeiro:     { name:'Padeiro',         cost:2, emoji:'👨‍🍳', desc:'Atordoa com pao',       hp:240,  dmg:55,  spd:58,  range:25,  atkRate:1.0, r:14, type:'melee',  color:'#d4a017', special:'stun',  stunDur:.8,  stunChance:.3 },
  mototaxista: { name:'Mototaxista',     cost:3, emoji:'🏍️',  desc:'Rapido e agil',         hp:130,  dmg:90,  spd:145, range:22,  atkRate:1.4, r:12, type:'melee',  color:'#e67e22' },
  cabeleireiro:{ name:'Cabeleireiro',    cost:4, emoji:'💈',  desc:'Cura aliados proximos',  hp:280,  dmg:45,  spd:52,  range:22,  atkRate:1.0, r:15, type:'melee',  color:'#e91e63', special:'heal', healR:85,  healAmt:18 },
  vereador:    { name:'Vereador',        cost:5, emoji:'🤵',  desc:'Tank, ataca torres',     hp:1200, dmg:105, spd:38,  range:28,  atkRate:1.5, r:22, type:'melee',  color:'#2c3e50', prio:'building' },
  gaucho:      { name:'Gaucho',          cost:4, emoji:'🤠',  desc:'Laco — atordoa em area', hp:380,  dmg:95,  spd:60,  range:30,  atkRate:1.1, r:15, type:'melee',  color:'#a0522d', special:'lasso', lassoR:90, stunDur:1.0 },
  zelador:     { name:'Zelador',         cost:5, emoji:'🧹',  desc:'Vassoura — dano em area', hp:900,  dmg:80,  spd:45,  range:50,  atkRate:.8,  r:20, type:'melee',  color:'#546e7a', special:'sweep', sweepR:55 },
  dancarina:   { name:'Dancarina',       cost:3, emoji:'💃',  desc:'Esquiva 25% dos ataques', hp:180,  dmg:50,  spd:80,  range:22,  atkRate:1.2, r:12, type:'melee',  color:'#ff69b4', special:'dodge', dodgeChance:.25 },
  policia:     { name:'Policial',        cost:3, emoji:'👮',  desc:'Gas de pimenta (AOE)',    hp:320,  dmg:70,  spd:62,  range:90,  atkRate:.8,  r:16, type:'ranged', color:'#1a3c6e', special:'gas',  gasR:55,  gasDmg:30 },
  professora:  { name:'Professora',      cost:3, emoji:'👩‍🏫', desc:'Buffa dano dos aliados',  hp:160,  dmg:35,  spd:55,  range:120, atkRate:.9,  r:13, type:'ranged', color:'#8e44ad', special:'buff', buffR:100, buffMult:1.4 },
  vendedor:    { name:'Vendedor Ambul.', cost:3, emoji:'🧃',  desc:'4 clientes de ataque',    hp:90,   dmg:38,  spd:85,  range:85,  atkRate:.9,  r:10, type:'ranged', color:'#16a085', count:4 },
  funkeiro:    { name:'Funkeiro',        cost:4, emoji:'🎤',  desc:'Som que atordoa (AOE)',   hp:200,  dmg:60,  spd:50,  range:130, atkRate:.7,  r:14, type:'ranged', color:'#9b59b6', special:'sonic', sonicR:70, stunDur:.6 },
  bombeiro:    { name:'Bombeiro',        cost:4, emoji:'🚒',  desc:'Mangueira — reduz vel.',  hp:350,  dmg:55,  spd:55,  range:100, atkRate:.7,  r:16, type:'ranged', color:'#f44336', special:'slow', slowR:65,  slowF:.5,  slowDur:1.5 },
  pescador:    { name:'Pescador',        cost:3, emoji:'🎣',  desc:'Puxa o inimigo para perto', hp:150,dmg:40,  spd:45,  range:120, atkRate:.6,  r:12, type:'ranged', color:'#00838f', special:'pull', pullDist:80 },
  estudante:   { name:'Estudante',       cost:2, emoji:'📚',  desc:'Buff continuo nos aliados', hp:120,dmg:30,  spd:55,  range:110, atkRate:1.0, r:11, type:'ranged', color:'#8e24aa', special:'buff', buffR:120, buffMult:1.3 },
  churrasco:   { name:'Bola de Fogo',    cost:4, emoji:'🔥',  desc:'Explosao de fogo (AOE)',  dmg:380, aoe:62, type:'spell', color:'#e74c3c' },
  ronda:       { name:'Ronda Policial',  cost:3, emoji:'🚨',  desc:'Raio de luz (AOE grande)', dmg:200, aoe:75, type:'spell', color:'#1565c0' },
  medico:           { name:'Medico',           cost:4, emoji:'🩺', desc:'Cura aliados proximos em combate',   hp:420,  dmg:48,  spd:54,  range:110, atkRate:0.9,  r:15, type:'ranged', color:'#1976d2', special:'heal',  healR:85,  healAmt:28, shopCost:5,  locked:true },
  advogado:         { name:'Advogado',         cost:3, emoji:'⚖️', desc:'Paralisa inimigos com argumentos',   hp:270,  dmg:72,  spd:60,  range:22,  atkRate:1.0,  r:13, type:'melee',  color:'#37474f', special:'stun',  stunDur:1.0, stunChance:0.40, shopCost:4,  locked:true },
  engenheiro:       { name:'Engenheiro',       cost:5, emoji:'👷', desc:'Tank solido, prioriza estruturas',   hp:1050, dmg:88,  spd:46,  range:30,  atkRate:1.4,  r:21, type:'melee',  color:'#f57f17', prio:'building', shopCost:6,  locked:true },
  garcom:           { name:'Garcom',           cost:3, emoji:'🍽️', desc:'Joga pratos — 3 projeteis ao mesmo tempo', hp:210,dmg:62, spd:72, range:110, atkRate:0.85, r:12, type:'ranged', color:'#4e342e', count:3, shopCost:3, locked:true },
  motorista_onibus: { name:'Motorista',        cost:5, emoji:'🚌', desc:'Onibus humano — blindado e lento',   hp:1350, dmg:95,  spd:38,  range:28,  atkRate:1.5,  r:24, type:'melee',  color:'#1565c0', prio:'building', shopCost:5,  locked:true },
  cantor:           { name:'Cantor',           cost:4, emoji:'🎤', desc:'Grito agudo que atordoa em area',    hp:240,  dmg:70,  spd:56,  range:135, atkRate:0.75, r:13, type:'ranged', color:'#ad1457', special:'sonic', sonicR:80,  stunDur:0.85, shopCost:4,  locked:true },
  ator:             { name:'Ator',             cost:2, emoji:'🎭', desc:'Esquiva 35% dos ataques inimigos',   hp:165,  dmg:58,  spd:92,  range:22,  atkRate:1.2,  r:12, type:'melee',  color:'#6a1b9a', special:'dodge', dodgeChance:0.35, shopCost:3, locked:true },
  pedreiro:         { name:'Pedreiro',         cost:3, emoji:'🧱', desc:'Arremessa tijolos pesados de longe', hp:290,  dmg:84,  spd:56,  range:100, atkRate:0.9,  r:14, type:'ranged', color:'#bf360c', shopCost:3,  locked:true },
  faxineiro:        { name:'Faxineiro',        cost:4, emoji:'🧹', desc:'Esfregao encharcado — desacelera',   hp:340,  dmg:62,  spd:52,  range:85,  atkRate:0.85, r:15, type:'ranged', color:'#00695c', special:'slow',  slowR:72,  slowF:0.45, slowDur:1.8, shopCost:4,  locked:true },
  encanador:        { name:'Encanador',        cost:3, emoji:'🔧', desc:"Cano d'agua — desacelera inimigos",  hp:260,  dmg:68,  spd:56,  range:95,  atkRate:0.85, r:13, type:'ranged', color:'#0277bd', special:'slow',  slowR:62,  slowF:0.50, slowDur:1.5, shopCost:3,  locked:true },
  veterinario:      { name:'Veterinario',      cost:4, emoji:'🐾', desc:'Cura aliados e invoca cachorro',     hp:360,  dmg:42,  spd:54,  range:105, atkRate:0.9,  r:15, type:'ranged', color:'#2e7d32', special:'heal',  healR:90,  healAmt:32, shopCost:5,  locked:true },
  seguranca:        { name:'Seguranca',        cost:4, emoji:'🛡️', desc:'Para-choque humano — vida altissima', hp:1100, dmg:82,  spd:40,  range:25,  atkRate:1.3,  r:22, type:'melee',  color:'#263238', shopCost:4,  locked:true },
  corretor:         { name:'Corretor',         cost:3, emoji:'🏠', desc:'Agil e persuasivo no corpo-a-corpo', hp:230,  dmg:82,  spd:118, range:22,  atkRate:1.1,  r:12, type:'melee',  color:'#e65100', shopCost:3,  locked:true },
  nutricionista:    { name:'Nutricionista',    cost:3, emoji:'🥗', desc:'Superalimentos — buffa aliados',     hp:200,  dmg:38,  spd:56,  range:125, atkRate:1.0,  r:12, type:'ranged', color:'#558b2f', special:'buff',  buffR:105, buffMult:1.45, shopCost:4, locked:true },
  mecanico:         { name:'Mecanico',         cost:4, emoji:'🔩', desc:'Chave inglesa — destroi estruturas', hp:440,  dmg:78,  spd:52,  range:22,  atkRate:1.1,  r:16, type:'melee',  color:'#546e7a', prio:'building', shopCost:4,  locked:true },
  carpinteiro:      { name:'Carpinteiro',      cost:3, emoji:'🪚', desc:'Martelo pesado — atordoa ao acertar', hp:315, dmg:102, spd:58,  range:22,  atkRate:1.0,  r:14, type:'melee',  color:'#6d4c41', special:'stun',  stunDur:1.2, stunChance:0.38, shopCost:4, locked:true },
  piloto:           { name:'Piloto',           cost:5, emoji:'✈️', desc:'Rasante aereo — dano poderoso a distancia', hp:460, dmg:168, spd:65, range:160, atkRate:0.65, r:16, type:'ranged', color:'#1a237e', shopCost:6, locked:true },
  cientista:        { name:'Cientista',        cost:5, emoji:'🔬', desc:'Acido em area — dissolve qualquer um', hp:310, dmg:148, spd:50,  range:130, atkRate:0.7,  r:14, type:'ranged', color:'#00838f', special:'gas',   gasR:65,   gasDmg:48, shopCost:6,  locked:true },
  influencer:       { name:'Influencer',       cost:3, emoji:'📱', desc:'Live viral — atordoa inimigos em area', hp:190, dmg:58,  spd:66,  range:125, atkRate:0.8,  r:12, type:'ranged', color:'#e91e63', special:'sonic', sonicR:65,  stunDur:0.7, shopCost:4,  locked:true },
  diretor_producao: { name:'Diretor de Producao', cost:10, emoji:'🎬', desc:'Lendario! Imbativel — vale 3 rodadas', hp:8000, dmg:480, spd:140, range:38, atkRate:0.5, r:26, type:'melee', color:'#ffd700', prio:'building', special:'stun', stunDur:0.9, stunChance:0.65, shopCost:50, locked:true, deckAdvance:3, legendary:true },
  ladrao:           { name:'Ladrao',             cost:4,  emoji:'🦹', desc:'Vampiro — cada golpe drena HP do alvo', hp:350, dmg:72, spd:92, range:25, atkRate:1.1, r:14, type:'melee', color:'#4a148c', special:'drain', drainPct:0.45 },
  ze_pelintra:      { name:'Ze Pelintra',        cost:8,  emoji:'🕺', desc:'Lendario — teleporta, cura e e quase indestrutivel', hp:5500, dmg:240, spd:125, range:30, atkRate:0.85, r:22, type:'melee', color:'#7b1fa2', special:'pilintra', healR:115, healAmt:80, dodgeChance:0.28, shopCost:40, locked:true, legendary:true },
};

export const SHOP_CARD_KEYS = [
  'medico','advogado','engenheiro','garcom','motorista_onibus','cantor',
  'ator','pedreiro','faxineiro','encanador','veterinario','seguranca',
  'corretor','nutricionista','mecanico','carpinteiro','piloto','cientista',
  'influencer','diretor_producao','ze_pelintra'
];

export const BASE_KEYS = Object.keys(CARDS).filter(k => !CARDS[k].locked);
